package netgloo.models;


import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.HashSet;
import java.util.Set;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "users")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's email
    @NotNull
    private String email;

    // The user's name
    @NotNull
    private String nachname;

    private String titel;
    private String vorname;

    private boolean enabled;
    private String telefon;
    private String art;
    @OneToOne
    private Adresse adresse;
    private Integer idBildgruppe;
    private String username;
    private String passwort;

    @OneToMany
    private Set<Bestellung> bestellung = new HashSet<>();

    private Role role;






    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String email, String nachname, String titel, String vorname, boolean enabled, String telefon, String art, Adresse adresse, Integer idBildgruppe, String username, String passwort, Set<Bestellung> bestellung, Role role) {
        this.email = email;
        this.nachname = nachname;
        this.titel = titel;
        this.vorname = vorname;
        this.enabled = enabled;
        this.telefon = telefon;
        this.art = art;
        this.adresse = adresse;
        this.idBildgruppe = idBildgruppe;
        this.username = username;
        this.passwort = passwort;
        this.bestellung = bestellung;
        this.role = role;
    }

    public Set<Bestellung> getBestellung() {
        return bestellung;
    }

    public void setBestellung(Set<Bestellung> bestellung) {
        this.bestellung = bestellung;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNachname() {
        return nachname;
    }

    public void setNachname(String nachname) {
        this.nachname = nachname;
    }

    public String getTitel() {
        return titel;
    }

    public void setTitel(String titel) {
        this.titel = titel;
    }

    public String getVorname() {
        return vorname;
    }

    public void setVorname(String vorname) {
        this.vorname = vorname;
    }


    public String getTelefon() {
        return telefon;
    }

    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    public String getArt() {
        return art;
    }

    public void setArt(String art) {
        this.art = art;
    }

    public Adresse getAdresse() {
        return adresse;
    }

    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }

    public Integer getIdBildgruppe() {
        return idBildgruppe;
    }

    public void setIdBildgruppe(Integer idBildgruppe) {
        this.idBildgruppe = idBildgruppe;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getUsername() {
        return username;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswort() {
        return passwort;
    }

    public void setPasswort(String passwort) {
        this.passwort = passwort;
    }


} // class User
